# Generated by Django 3.2.4 on 2022-02-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colourants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=200)),
                ('pigment', models.CharField(max_length=200)),
                ('techniques', models.CharField(max_length=500)),
                ('chronology_from', models.IntegerField(blank=True, null=True)),
                ('chronology_to', models.IntegerField(blank=True, null=True)),
                ('archeological_context', models.TextField(max_length=1000)),
                ('context', models.CharField(blank=True, max_length=200)),
                ('references', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('location', models.TextField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('affiliation', models.CharField(blank=True, max_length=200)),
                ('public_available', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('check', models.BooleanField(default=False)),
            ],
        ),
    ]
