# Generated by Django 3.2.4 on 2022-02-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colourants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=200)),
                ('pigment', models.CharField(max_length=200)),
                ('techniques', models.TextField(blank=True, max_length=4000)),
                ('chronology_from', models.IntegerField(blank=True, null=True)),
                ('chronology_to', models.IntegerField(blank=True, null=True)),
                ('archeological_context', models.TextField(blank=True, max_length=4000)),
                ('category_of_find', models.TextField(max_length=4000)),
                ('references', models.TextField(blank=True, max_length=4000)),
                ('notes', models.TextField(blank=True, max_length=4000)),
                ('location', models.TextField(blank=True, max_length=4000)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('affiliation', models.TextField(blank=True, max_length=4000)),
                ('publicly_available', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('check', models.BooleanField(default=False)),
            ],
        ),
    ]
