# Generated by Django 3.2.4 on 2022-02-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colourants',
            old_name='public_available',
            new_name='publicly_available',
        ),
    ]
